### ISSUE TITLE
Substitution with visual mode doesn't work (I'd like to contribute)

### ISSUE THREAD

**Issue by dillonforrest** [lloeki/ex-mode#100]
Great work with ex-mode! I started using it a few weeks ago and am loving it. I'd like to contribute to your work here!

I noticed that `:s` doesn't work with visual mode. In vim, it's very useful to highlight a section of the code with visual mode, then use `:s` to substitute just the range selected. Vim will expand visual mode + `:s` to `:'<,'>s`.

I use visual mode + substitution all the time and would love to add that to ex-mode. Any tips on how I can get started?

**Comment by lloeki** [comment]
I'm *really* short on time but you seem quite motivated, so here's a real quick pointer (@jazzpi, please correct me) from the top of my head. Look for marks (VimState?) and Atom's selection start and end. Setting `'<` and `'>` marks properly should do the trick.

**Comment by jazzpi** [comment]
The marks are just `<` and `>`, other than that it should be the way to do it. I think it would be better suited to vim-mode itself since the `<` and `>` marks are not specific to the ex line.

**Comment by dillonforrest** [comment]
@lloeki @jazzpi Thanks much for the quick replies! I just looked through the source, and I agree that this is something that should be handled in vim-mode.

**Comment by jontonsoup** [comment]
@dillonforrest is there an issue in vim-mode that corresponds to this? It still does not seem to be implemented?

**Comment by jazzpi** [comment]
Yes, atom/vim-mode#597. I might have a look into it  soon since I seem to have a bit of free time on my hands.
