### ISSUE TITLE
Are the Commands Documented Anywhere?

### ISSUE THREAD

**Issue by bookercodes** [lloeki/ex-mode#101]
Are the supported commands documented anywhere?

At the moment I am using the code as documentation.

**Comment by plbowers** [comment]
An old thread, but I concur it would be nice if someone documented what is/isn't implemented as compared to ex-mode in "real" vim...

**Comment by plbowers** [comment]
I went ahead and did it - see the wiki. (No details - if someone needs details then they should probably be looking for a vim tutorial rather than for a list of what commands are implemented.)

**Comment by bookercodes** [comment]
Nice one 👍
