### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by rgbkrk** [lloeki/ex-mode#105]
Just wanted to say thank you for this package, it is what finally kicked me over to using Atom fulltime (with both vim-mode + ex-mode).

:smile:

**Comment by rgbkrk** [comment]
Since I've thanked you, I can close it too. :wink:

**Comment by lloeki** [comment]
Great to hear! Thanks!

**Comment by alexbooker** [comment]
I would like to say *thank you* as well!

**Comment by brujo-rojas** [comment]
Thanks 😄

**Comment by lloeki** [comment]
Relaying this to @jazzpi since he's the current maintainer, and this will surely cheer him up as much as I ;-)

**Comment by jazzpi** [comment]
I've seen it before but it cheers me up every time :smile:
