### ISSUE TITLE
Vim-mode-plus support

### ISSUE THREAD

**Issue by Deph0** [lloeki/ex-mode#111]
Hi, I'd like to know if it's possible to make this amazing package compatible with vim-mode-plus, which seems to have a lot more features then the parent 'vim-mode'.

```
ref: https://atom.io/packages/vim-mode-plus
Following packages for vim-mode won't work in vim-mode-plus.
Why? Because service API name is different.
It's easy to add support I believe. Please report to each project.

* [...]
* ex-mode
* [...]
```

**Comment by sibevin** [comment]
A workaround: Add the following settings in your keymap.cson

```
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  ':': 'ex-mode:open'
```

**Comment by jordwalke** [comment]
Thanks for the workaround @sibevin. It would be great to get this added by default.

**Comment by jazzpi** [comment]
Also, vim-mode-plus doesn't provide the `VimMode` service but instead the `VimModePlus` service which breaks interacting with the search history (#128).

**Comment by brujo-rojas** [comment]
the keymap is not working in atom 1.10.2 😢

**Comment by jazzpi** [comment]
I can't test now, but did this work for you before? And what does the keybind resolver show when you press <kbd>:</kbd>? (Bring it up with <kbd>Ctrl+.</kbd>)

**Comment by brujo-rojas** [comment]
yes, it was working in the earlier version, I've try with `ctr+.`and also does not work.

**Comment by brujo-rojas** [comment]
I try to use `:`with another command and does work, and I execute ex-mode:open with `cmd+shift+p`and also does work, I don't know why not work

**Comment by luisdavim** [comment]
This is working now, I think this issue can be closed.

**Comment by hultberg** [comment]
Follow up of @luisdavim, this package supports vim-mode-plus. If there are any more issues, please repo them in a new issue.
