### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by lloeki** [lloeki/ex-mode#116]
I now only rarely use Atom and am looking for a new maintainer for this project. Please chime in.

**Comment by lloeki** [comment]
@jazzpi do you feel like this could be of interest to you?

**Comment by jazzpi** [comment]
I still use Atom regularly and I think I know how this package works by 
now, but I don't really work on ex-mode too often anymore. I guess I 
could at least merge PRs and test them for a bit though since I use the 
package pretty much daily, so I would take it up if no one else wants too.

**Comment by bakert** [comment]
What do you use instead? :D

**Comment by lloeki** [comment]
@jazzpi I added you as a collaborator :-)

**Comment by jazzpi** [comment]
Alright, thanks :smile:

**Comment by rgbkrk** [comment]
Thanks @jazzpi, now that I know about the need for maintenance I'll peer in sometimes. I mostly wondered what the upgrades were after 0.8.0 came out. :smile:

**Comment by rgbkrk** [comment]
It would be cool if Atom would pick up this package formally, since [`vim-mode`](https://github.com/atom/vim-mode) is directly supported.

**Comment by CHIEFnChowCombo** [comment]
DUDE!! I'll pick it up!  I came here to file a bug for ex-mode, and was shocked to find that you had written it.  I keep swapping back and forth between vim and atom.

**Comment by lloeki** [comment]
Hah, cool :-) Super busy right now but if @jazzpi doesn't oppose, I'll add you as a collab for now.

**Comment by jazzpi** [comment]
No objections, more people working on this can't hurt :smile:

**Comment by lloeki** [comment]
Welcome, @CHIEFnChowCombo.

**Comment by vivek-nandyala** [comment]
Hai , i am entirely new to atom. In my VIM world I do use :column , :sort , :set nowrap, etc commands very often . Can i request you guys to add them to the ' : ' please. 

I am new to .js and .coffee too , but to make atom the best ever editor (One day when I can just copy my vimrc to atom) , this seems to be a good enough motivation to pick up a new language :)

**Comment by hultberg** [comment]
@vivek-nandyala Hello. You can open new issues for your requests and PR are welcomed
