### ISSUE TITLE
Typing : to activate Ex mode spawns a bunch of lines

### ISSUE THREAD

**Issue by johnelliott** [lloeki/ex-mode#123]
This package is the only reason I open atom :)

I just updated to the latest version and noticed this when I hit : a bunch in normal mode:

![image](https://cloud.githubusercontent.com/assets/5633265/12151654/3ce43d96-b47e-11e5-89af-608cb9cbcfd7.png)

Anyone else experience this?

**Comment by jazzpi** [comment]
I can't reproduce this. Do the lines not get focussed when you press `:`? If so, can you see what command is getting triggered when pressing `:` by first pressing Ctrl-. to bring up the key binding resolver?

Also, can you reproduce this with only vim-mode and ex-mode enabled and all other community packages disabled?

**Comment by johnelliott** [comment]
Hi @jazzpi. They each spawned but did not get focus. I could move focus there with the mouse and subsequently use my esc key to get them to go away. I can try to open some browser tools tomorrow and see if I'm getting any output there.

**Comment by johnelliott** [comment]
Closing because now I can't duplicate this on my other machine. If I catch this again I'll do a better capture and reopen this.
