### ISSUE TITLE
: maps to /

### ISSUE THREAD

**Issue by aericson** [lloeki/ex-mode#127]
Hello,

this might not be a bug from ex-mode but something else, but maybe someone can give me a guide to where this bug should be filled. Pressing ':' on my keyboard layout (Brazilian) maps to '/' (find) and I can't type commands. Instead I have to press "ç" key to get to the ex ':' command input.

Attaching a picture of the keyboard layout.
![900px-kb_portuguese_brazil svg](https://cloud.githubusercontent.com/assets/692542/12757902/bf236c88-c9b8-11e5-958e-7f50a97d8cc0.png)

Any hints on where else this bug should be filled would be greatly appreciated.
Thanks!

**Comment by jazzpi** [comment]
This is a [known issue](https://github.com/atom/atom-keymap/issues/37) with the underlying architecture, but you can use the [keyboard-localization](https://atom.io/packages/keyboard-localization) package to fix this issue (and probably many more with other keybindings).

**Comment by aericson** [comment]
Thanks!
