### ISSUE TITLE
Implement tab commands

### ISSUE THREAD

**Issue by cpadilla** [lloeki/ex-mode#13]
Currently ex-mode is missing functionality for opening/closing new tabs. This includes:
:tabnew
:tabe
:tabc

We're also missing tab navigation with:
:tabn
:tabp

[Full vim documentation](http://vimdoc.sourceforge.net/htmldoc/tabpage.html)

**Comment by cpadilla** [comment]
I'll actually work on this feature since it seems pretty manageable.

**Comment by lloeki** [comment]
`:tabe` is done, and should be the same as `:tabnew`. `:tabc` should be a synonym of `:q`.
