### ISSUE TITLE
Maintainer update

### ISSUE THREAD

**Issue by LongLiveCHIEF** [lloeki/ex-mode#151]
I've spent the time finally committing the file explorer motions and commands to muscle memory, and that was the last thing keeping me from ever using anything other than VIM.

I focus on helping to maintain libraries I personally make use of, and since I will no longer need to make use of this, I'd like to be removed from maintainer role.

It was a pleasure working on this!

**Comment by lloeki** [comment]
It was a real pleasure too, thanks for everything!
