### ISSUE TITLE
Update PR template

### ISSUE THREAD

**Issue by jazzpi** [lloeki/ex-mode#161]
I don't really like using checkboxes for the test list, it makes every PR look like an unfinished WIP.

I'm also watching this repository so I don't need to be @mentioned every time. @LongLiveCHIEF - since you aren't maintaining this project anymore, do you want to get a notification for every pull request or should I also take you out?

**Comment by LongLiveCHIEF** [comment]
Scratch me from the template

On Aug 15, 2016 2:32 PM, "Jasper v. B." <notifications@github.com> wrote:
>
> I don't really like using checkboxes for the test list, it makes every PR
look like an unfinished WIP.
>
> I'm also watching this repository so I don't need to be @mentioned every
time. @LongLiveCHIEF - since you aren't maintaining this project anymore,
do you want to get a notification for every pull request or should I also
take you out?
