### ISSUE TITLE
:[line-number] line number out of range error

### ISSUE THREAD

**Issue by DepthDeluxe** [lloeki/ex-mode#169]
In vim, the feature `:[line-number]` where the specified line number is greater than the number of lines in a file moves the cursor to the end of the file.

In ex-mode, I get a `Command error: line out of range`.  It would be nice if this feature exactly copied the vim's functionality.

ex-mode 0.13.0
Atom 1.11.1, OSX

**Comment by jazzpi** [comment]
Should be fixed in 0.13.1, please try updating ex-mode and restarting Atom.

**Comment by DepthDeluxe** [comment]
Looks like it is fixed, thank you!
