### ISSUE TITLE
Looking for a new maintainer... Again

### ISSUE THREAD

**Issue by jazzpi** [lloeki/ex-mode#174]
So I have also run into the same issue as @lloeki and @LongLiveCHIEF and now no longer really use Atom and don't have the time/energy to maintain this project. If anyone wants to continue maintaining this package, please do pitch in!

**Comment by LongLiveCHIEF** [comment]
Vim `#FTW`?

**Comment by intijk** [comment]
:(

 y you give up using atom

**Comment by awilkins** [comment]
Would it be rude to ask @t9md to think about it? :pray:

**Comment by awilkins** [comment]
Hey there @hultberg - you forked it, do you want The POWER?

**Comment by hultberg** [comment]
@awilkins Sure, I could give it a try. 😄

**Comment by lloeki** [comment]
@awilkins thanks for the ping, I've been meaning to ask just that since like forever. Good luck @hultberg.

**Comment by hultberg** [comment]
@lloeki Great, thanks. Closing this issue.

**Comment by jazzpi** [comment]
Thank you so much! I too wish you good luck and I'll see if I ever get around to getting a working 1.19 build :grimacing:
