### ISSUE TITLE
Command text not visible in bottom panel

### ISSUE THREAD

**Issue by andischerer** [lloeki/ex-mode#19]
The bottom command panel is showing up(`:`) but any command text i type is not visible. When i submit the command it executes successfully.

![2015-03-07 20_52_59-ex-command-mode-input-view coffee - c__users_as_github_ex-mode - atom](https://cloud.githubusercontent.com/assets/930604/6543043/5e437266-c50c-11e4-9491-ca43ddd80d14.png)

Atom 0.186

**Comment by ahmadseleem** [comment]
Yes, it's still not visible for me either...

**Comment by lloeki** [comment]
This is not released yet. Sorry for the delay.

**Comment by lloeki** [comment]
0.3.1 published.
