### ISSUE TITLE
`:wqa` closes the window in addition to closing all tabs

### ISSUE THREAD

**Issue by tmelz** [lloeki/ex-mode#206]
To repro:

1. Open new window
2. Open a file (only one tab open)
3. `:wqa`

Expected: all tabs close, the window stays open.
Actual: all tabs close and the window closes.

Having the window close, especially without prompting is fairly destructive.

To be fair, I usually type `:wqa` by accident, so as a personal workaround I'm aliasing `wqa` to just `wq`. But I think this behavior should change globally to simply close the tabs..

**Comment by hultberg** [comment]
@tmelz This has been fixed with #209. Will be released soon.
