### ISSUE TITLE
border-radius doesn't look good....

### ISSUE THREAD

**Issue by ahmadseleem** [lloeki/ex-mode#24]
I hope the border-radius would be removed.
It doesn't look good in my opinion for that bar. and maybe an option to choose the color of the bar would be great, too.

Thanks!

**Comment by lloeki** [comment]
This view was taken straight from vim-mode's `/`. I don't like it either, especially with One themes, but the choice is either to have it differ from vim-mode or ultimately somehow reuse their view. So, same defaults make sense.

An alternative I considered was to implement a much nicer yet more Atom-ish palette, especially for wildmenu-like real parse+autocomplete stuff (not just fuzzy match on a fixed list, more like bash/zsh-completions). This definitely has my vote, but needs much more work.

Anyway, this is totally stylable, so try this in your `styles.less` file:

```less
.editor.mini {
  border-radius: 0;
}
```

**Comment by ahmadseleem** [comment]
Cool!, Thanks!
