### ISSUE TITLE
Package not available in latest Atom

### ISSUE THREAD

**Issue by Valve** [lloeki/ex-mode#28]
I'm trying to install it, but can't find it:

My atom version is 0.188.0 on OSX 

![skitch](https://cloud.githubusercontent.com/assets/27387/6863900/99b9a03c-d46a-11e4-9f90-ed216b310174.png)

**Comment by jazzpi** [comment]
You are searching the Installed Packages.

Click on Install in the sidebar if you want to install packages, this got me a few times too.

**Comment by Valve** [comment]
Oh, dumb I have been, thanks, closing )
