### ISSUE TITLE
Implement go to line

### ISSUE THREAD

**Issue by Valve** [lloeki/ex-mode#33]
In vim its possible to do :<line number> to go to that line

**Comment by jazzpi** [comment]
Duplicate of #25 and fixed in #26 (should be in 0.4.1)

**Comment by Valve** [comment]
oh, thanks, jazzpi

**Comment by jazzpi** [comment]
But just by the way - you could just do `24G` :wink:

**Comment by Valve** [comment]
@jazzpi , oh nice, didn't know about this one. I always do it with :24
