### ISSUE TITLE
Object.add is deprecated.

### ISSUE THREAD

**Issue by walalapancho** [lloeki/ex-mode#41]
currently i use atom 0.199.0, with vim-mode and ex-mode.  i obtain this warning from deprecation cop: 

Are you trying to listen for the 'core:confirm' Atom command with `jQuery::on`?
`jQuery::trigger` can no longer be used to listen for Atom commands. Please
use `atom.commands.add` instead. See the docs at
https://atom.io/docs/api/latest/CommandRegistry

thanks in advance,

**Comment by lloeki** [comment]
Thanks for the report, tracked as #42, and closed as of v0.5.0. Please notify me of any other non-compliance!
