### ISSUE TITLE
Support :s

### ISSUE THREAD

**Issue by mkhoeini** [lloeki/ex-mode#5]
Maybe it is the most important ex command which I use.

**Comment by jazzpi** [comment]
I'm currently working on a PR for this. This requires some changes to the underlying structure however, so it might take a while.

**Comment by lloeki** [comment]
I attempted something, but don't know Atom's API very well and I'm short on time. Let's see what you can come up with, just make sure it behaves like vim. Regarding structural changes, at the very least it'll give some ideas. Remember that we can now access vim-state's info so we could even handle `'<,'>` in the future command line parser.

**Comment by lloeki** [comment]
Oops, bad click, sorry.
