### ISSUE TITLE
Can't enter ex-mode 

### ISSUE THREAD

**Issue by enric612** [lloeki/ex-mode#50]
I install vim-mode and ex-mode but when i press : nothing happens and if i press w the line are indented...
What im doing wrong?
Thanks!

**Comment by jazzpi** [comment]
What does the keybinding resolver (`Ctrl-.`) show when you press `:`? It should look like this:
![Keybinding resolver for `:`](http://i.imgur.com/bJ0hnfC.png)

**Comment by enric612** [comment]
Wow exactly thanks! I use spanish keyboard. Tomorrow i will try it and tell you.
Thanks bro!

**Comment by enric612** [comment]
It works! Perect. Thanks!

**Comment by phorust** [comment]
If your problem is solved, you should close this issue @enric612.
