### ISSUE TITLE
Vim like tab completion

### ISSUE THREAD

**Issue by dbooom** [lloeki/ex-mode#52]
It would be super helpful to add tab completion support for ex-mode, like in real vim.
It probably can be implemented as separate package, however ex-mode should provide more unified way to register and list all registered commands.

What do you guys think?

**Comment by jazzpi** [comment]
Yes, tab completion is definitely a goal, and I think it should definitely be in this package.
I tried starting work on this, but it's a bit painful the way commands are currently implemented.

See #29 and #49, too.

**Comment by lloeki** [comment]
Closing this in favour of #29.
