### ISSUE TITLE
Display initial ':' when ex mode activates

### ISSUE THREAD

**Issue by ardrigh** [lloeki/ex-mode#60]
I just installed the vim mode and ex mode packages to try.

First thing I noticed when using ex mode, hitting <kbd>:</kbd> opens a command bar, but it doesn't display the <kbd>:</kbd> at the start of the line.

Vim does this so you can visually check the commands you are entering are correct e.g. <kbd>:</kbd> activates ex then <kbd>w</kbd> displays as <kbd>:w</kbd> for write

ex mode accepts <kbd>:</kbd> then <kbd>w</kbd> for write, and also <kbd>:</kbd> then <kbd>:w</kbd> for write. So the actual function doesn't seem to break.

It's a minor thing, but it would be clearer if the bar displayed the initial <kbd>:</kbd> used to activate ex mode.

**Comment by jazzpi** [comment]
You can achieve that by putting this in your `styles.less`:
```less
.command-mode-input atom-text-editor[mini]::before {
  content: ":";
}
```

You could also put it in `ex-mode/styles/ex-mode.less` and submit a PR... :wink:

**Comment by ardrigh** [comment]
I just created PR #61 for this then.

**Comment by lloeki** [comment]
This is somehow tied to [this issue](https://github.com/atom/vim-mode/issues/596) for consistency reasons.
