### ISSUE TITLE
Support for vim option set list/set nolist

### ISSUE THREAD

**Issue by nzyuzin** [lloeki/ex-mode#68]
Is it possible to support `:set list`, an option which shows invisible characters such as line endings and tab characters, and `:set nolist` that turns this option off?

In the code I see no support for vim options and I wonder if ex-mode plans to have support for them. 

My typical use case for that command was to check whether file is tab or space indented. I noticed that there's `Window: Toggle Invisibles` for that in Atom, which is not bound to any key by default. Still I find it handy to use old vim command for that.

I could implement that option myself but firstly I want to clarify if vim options is appropriate functionality to have in ex-mode.

**Comment by lloeki** [comment]
This is planned ([no]list is one of my most used options), see #8. Unfortunately I'm super busy these times around. Any contribution is welcome!
