### ISSUE TITLE
Add specs

### ISSUE THREAD

**Issue by WhiteVoidia** [lloeki/ex-mode#79]
This package is in dire need of some [specs](https://atom.io/docs/latest/writing-specs) to prevent against major regression bugs such as #75 

Can also use Travis-CI to automate testing (see: http://blog.atom.io/2014/04/25/ci-for-your-packages.html)

**Comment by lloeki** [comment]
You bet. Contributions welcome.

**Comment by WhiteVoidia** [comment]
I'm currently looking into it on my own fork, though this is my first foray into atom packages so it will take a bit :)

**Comment by lloeki** [comment]
Ah, I knew I've been talking about unit tests [somewhere](https://github.com/lloeki/ex-mode/issues/44#issuecomment-106727034) already!

**Comment by jazzpi** [comment]
I'm currently working on moving the specs from atom/vim-mode#762 over here, shouldn't take too long hopefully :smile:

**Comment by lloeki** [comment]
Fantastic! :smile:

**Comment by lloeki** [comment]
Closing in favour of #83.
