### ISSUE TITLE
Missing colon in command bar

### ISSUE THREAD

**Issue by flz** [lloeki/ex-mode#86]
I found it pretty confusing that ':' wouldn't appear after I hit Esc-':'. I think it would be good just for visual effect anyway.

**Comment by jazzpi** [comment]
This should actually be working since #61 was merged, but it looks like themes might mess with it. Are you using the `atom-material-ui`/`-syntax` themes by chance?

**Comment by flz** [comment]
I am and you're right, it works with Atom Light for example.
