### ISSUE TITLE
replace with \t doesn't work

### ISSUE THREAD

**Issue by ghost** [lloeki/ex-mode#93]
running :%s/ - /\t/ig
turns 
PO_HDR Purchase Order Header- Header Record for Purchase Order
into 
PO_HDR Purchase Order HeadertHeader Record for Purchase Order
instead of replacing the "-" with a tab character? Is this user error?

**Comment by lloeki** [comment]
Escape sequences are not turned into control characters... yet.

**Comment by jazzpi** [comment]
Fixed in ddbdb86
