### ISSUE TITLE
New installation of Atom and ex-mode doesn't appear to do anything.

### ISSUE THREAD

**Issue by pnunn** [lloeki/ex-mode#95]
Hi there,

must be missing something here, but I've installed vim-mode and that seems to be working fine, but ex-mode seems to have no effect on the editor at all. Typing ":" makes no changes at all.  Any ideas?

**Comment by lloeki** [comment]
Using some [specific keyboard layout](https://github.com/lloeki/ex-mode/issues/50)? Maybe try to bind to another key or use [keyboard-localization](https://atom.io/packages/keyboard-localization).

**Comment by pnunn** [comment]
Ahh... could be, I use a US keyboard but with a DVORAK mapping. How do I find out what the key for : should be?

**Comment by lloeki** [comment]
Either via the keyboard resolver (package -> keyboard resolver -> toggle, then press `: `) or using keyboard-localization's layout generator (which doesn't include dvorak yet, but you could contribute it back!)

**Comment by pnunn** [comment]
OK, the resolver shows a degrees symbol (as in 23 degrees). How do I map that. I could do a layout, do I need to map every key? Not sure how I work out what's different to the normal us layout.

**Comment by lloeki** [comment]
To map it simply, you can paste this in your `keymap.cson`:

```
'atom-text-editor.vim-mode:not(.insert-mode)':
  '°': 'ex-mode:open'
```

Change the `°` if that's not the correct character.

If you're up to doing the layout instead, according to [QWERTY](https://en.wikipedia.org/wiki/QWERTY#US-International) and [Dvorak](https://en.wikipedia.org/wiki/Keyboard_layout#Dvorak) the only keys that *don't* change are `A`, `M`, `\``, `~`, `1` through `0` and their shift'd/alt'd symbols, along with `\` and `|`.

**Comment by pnunn** [comment]
Hmm... that didn't seem to have any effect at all. I'm not convinced ex-mode is actually live (but I may be wrong).

**Comment by lloeki** [comment]
What is the output of running `atom.packages.loadedPackages['ex-mode']` in a dev console?

**Comment by pnunn** [comment]
OK, that seems to have fired it up. So that's not the problem, must be the key mapping still.

**Comment by lloeki** [comment]
Did you try to map it to any other key or combination, just for testing?

**Comment by pnunn** [comment]
OK, mapped it to 'alt-a' and it works. How do I copy the character I'm getting in the keyboard-resolver. It must be something that looks like the degrees symbol but isn't.

**Comment by lloeki** [comment]
A hackish way to get it is to open the inspector and use the magnifying glass to inspect the DOM around the key binder resolver output. You'll be able to select and copy whatever has been pinpointed in the DOM tree.

**Comment by pnunn** [comment]
OK, that did it... the character is °, which in the editor has an underline under it that's not showing up here frustratingly.. Thanks so much.. seems to be good now.

**Comment by lloeki** [comment]
Gladd to hear that! Hope you'll enjoy it.
