### ISSUE TITLE
Autocomplete for files

### ISSUE THREAD

**Issue by LoLei** [lloeki/ex-mode#96]
It would be nice to have the `:e <filename>` (also `:b`, etc.) commands autocomplete your file names if you press tab.

Right now when I press tab at any time the command window is open it just closes it.

**Comment by LoLei** [comment]
If there already is a package which complements this feature please let me know

**Comment by lloeki** [comment]
duplicate of #13.

**Comment by LoLei** [comment]
https://github.com/lloeki/ex-mode/issues/13 is an entirely different issue, from my understanding.

He was asking for `:tab` commands, while I'm asking for autocompletion of file names in commands.

Typing `:tabnew ind` and pressing the tabulator key because I want it to autocomplete to `:tabnew index.html`, it just closes the command window. (`index.html` exists in the project.)

**Comment by lloeki** [comment]
Sorry, I meant #29.

**Comment by LoLei** [comment]
Ah okay, this is a duplicate then, my bad.
