### ISSUE TITLE
Command Bar broken/not showing

### ISSUE THREAD

**Issue by EntilZha** [lloeki/ex-mode#97]
I have the most recent version of atom, vim-mode, and ex-mode. It seems like functionality such as `:w` is broken. If I press `:` nothing happens. This used to work a few weeks ago, I just came back from vacation and started working (in Atom) again and found it not working.

**Comment by EntilZha** [comment]
Can anyone confirm they are having the same problem? I would like to at least figure out if its a problem with the latest release or something specific to my installation/selection of packages/etc

**Comment by ScriptorNY** [comment]
I have never used this package before. I just installed it and nothing happened for me either when using `:`.

**Comment by lloeki** [comment]
> I would like to at least figure out if its a problem with the latest release or something specific to my installation/selection of packages/etc

@EntilZha try to move/rename `.atom` folder, start atom again and install only `vim-mode` and `ex-mode`.

@ScriptorNY do you have a non-US keyboard layout?

**Comment by EntilZha** [comment]
That works for me, so it must be a conflict with another package. Guess its whackamole time to find out whats causing it.

**Comment by EntilZha** [comment]
I tried disabling all packages except for vim-mode and ex-mode, that didn't help. How could I look at the debug log to see if there is something obvious?

**Comment by lloeki** [comment]
Pop up the console in the developer tools. Also, try the keybinding resolver package.

**Comment by EntilZha** [comment]
Tried both with no luck, guess I have to do it the "old fashioned way"

**Comment by EntilZha** [comment]
Figured it out. I tried using the command palette to find `ex-mode` and nothing showed up. So I uninstalled and re-installed the package then it started to work. I don't know why it broke in the first place, maybe the upgrade was messed up somehow.

**Comment by ScriptorNY** [comment]
Okay, so I found the problem: it was due to my keyboard. It's a german keyboard. Everything works well now, and thank you very much for the precious help.

**Comment by lloeki** [comment]
Cool. Closing, then.
